### ISSUE TITLE
Retry configuration: Error communicating with API: TimeoutError()

### ISSUE THREAD

**Issue by Mick51** [ofalvai/home-assistant-candy#60] opened 2022-02-10 13:43 UTC
Why does it not detect when the dryer is off ? This creates a lot of errors in home assistant ..... It would be nice to solve the problem otherwise I will have to remove this extension.

![Capture d’écran 2022-02-10 134701](https://user-images.githubusercontent.com/40418405/153419655-d9a9b2d6-fc4b-44b9-9bba-cbf2f0fcaaeb.jpg)

`Réessayer la configuration: Error communicating with API: TimeoutError()`

`2022-02-10 13:35:17 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 0.3s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])
2022-02-10 13:35:20 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 1.5s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])
2022-02-10 13:35:23 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 2.0s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])
2022-02-10 13:35:26 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 1.6s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])
2022-02-10 13:35:29 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 10.9s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])
2022-02-10 13:35:43 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 19.3s
Why does it not detect when the dryer is off? This creates a lot of errors in home assistant ..... It would be nice to solve the problem otherwise I will have to remove this extension.

(aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])`

2022-02-10 13:34:44 INFO (MainThread) [custom_components.candy.client] Backing off status_with_retry(...) for 5.4s (aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.47:80 ssl:default [Connect call failed ('192.168.1.47', 80)])`

**Comment by Mick51** [comment] 2022-04-23 07:50
??? 🤔

**Comment by atlaspl** [comment] 2022-05-07 17:17
I have the same issue

**Comment by ofalvai** [comment] 2022-11-13 15:55
This is a duplicate of #12. Please see the details in that thread

**Closed by ofalvai** 2022-11-13 15:55 UTC
