### ISSUE TITLE
API: ValueError("Unrecognized code when parsing <enum 'DryerProgramState'>: 1")

### ISSUE THREAD

**Issue by Mick51** [ofalvai/home-assistant-candy#103] opened 2022-04-23 08:16 UTC
Réessayer la configuration: Error communicating with API: ValueError("Unrecognized code when parsing <enum 'DryerProgramState'>: 1")

?????????????

**Comment by ofalvai** [comment] 2022-06-27 06:09
Looks like your device reports a new program state value (1) that this integration can't handle. Can you help us understand when do you see this status (what phase of the dryer program)?

For reference, here are the program state values that are currently recognized: https://github.com/ofalvai/home-assistant-candy/blob/dd96c43a4b8d6c0836559452ad2d839bb7ba52e4/custom_components/candy/client/model.py#L72

**Comment by ofalvai** [comment] 2022-11-13 15:55
It's actually a duplicate of #59

**Closed by ofalvai** 2022-11-13 15:55 UTC
